services:
  - type: web
    name: marfani-steels-reporting-deck
    env: node
    plan: free
    autoDeployTrigger: commit
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: LIVE_WORKBOOK_URL
        value: https://marfanisteelpvtltd-my.sharepoint.com/:x:/g/personal/dms-msgroup_marfanisteel_com/IQAkxFhUOv2wQIdzGqC5p7__AbGgQ5ZzHygvbIro73t1xSA?download=1
      - key: DATABASE_URL
        fromDatabase:
          name: marfani-users-db
          property: connectionString

databases:
  - name: marfani-users-db
    plan: free
    databaseName: marfani_users
    user: marfani_app
