services:
  - type: web
    name: marfani-steels-reporting-deck
    env: node
    plan: free
    autoDeployTrigger: commit
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: ENABLE_LIVE_WORKBOOK
        value: "true"
      - key: LIVE_WORKBOOK_URL
        value: https://www.dropbox.com/scl/fi/fiiy3o6coteasonzw49tu/New-Import-Monitoring.xlsx?rlkey=kml4r6k2dtcq9c0bjw7ambt6o&st=zrxjnwlq&dl=0
      - key: DATABASE_URL
        fromDatabase:
          name: marfani-users-db
          property: connectionString

databases:
  - name: marfani-users-db
    plan: free
    databaseName: marfani_users
    user: marfani_app
